version: "2.1"
services:
  orders:
    image: shop-example-orders
    environment:
      DB_HOSTNAME: orders-db
      DB_USERNAME: orders
      DB_PASSWORD: secret
      DB_DATABASE: orders
      SECRET_KEY: "l1jp*8SggVjlWpGI5QkFG3UUB&ob@lY@s4v^h83&Rv7YjI4yD8FqENTr^6ju40Cz"
    ports:
      - "8080:8080"

  orders-db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: secret

